name: CI Pipeline

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-asyncio httpx pytest-cov

      - name: Check Syntax
        run: python -m compileall .

      - name: Run Tests and Generate Coverage
        run: |
          # --cov=. covers all files
          # --cov-report=html:reports/ creates an HTML coverage report in the 'reports/' folder
          pytest --maxfail=5 --disable-warnings --cov=. --cov-report=html:reports/ tests/

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: reports/
