name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy to Windows Server
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          USER: ${{ secrets.USER }}
        run: |
          if [[ -z "${{ secrets.SSH_PRIVATE_KEY }}" ]]; then echo "❌ SSH_PRIVATE_KEY is missing"; else echo "✅ SSH_PRIVATE_KEY is set"; fi
          if [[ -z "${{ secrets.SERVER_IP }}" ]]; then echo "❌ SERVER_IP is missing"; else echo "✅ SERVER_IP is set"; fi
          if [[ -z "${{ secrets.USER }}" ]]; then echo "❌ USER is missing"; else echo "✅ USER is set"; fi

          echo "$SSH_PRIVATE_KEY" > deploy_key.pem
          icacls deploy_key.pem /inheritance:r
          icacls deploy_key.pem /grant:r "$($env:khalil):(R)"

          ssh -v -o StrictHostKeyChecking=no -i deploy_key.pem khalil@192.168.212.164 powershell << 'EOF'
            cd C:\Users\DELL\Desktop\fastapi-book-project
            
            git pull origin main
            
            C:\Users\DELL\Desktop\fastapi-book-project\venv\Scripts\python.exe -m pip install -r requirements.txt
            
            taskkill /F /IM python.exe || echo "No FastAPI process running"
            start /B "" "C:\Users\DELL\Desktop\fastapi-book-project\venv\Scripts\uvicorn.exe" main:app --host 0.0.0.0 --port 8000
          EOF
