name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          USER: ${{ secrets.USER }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
        run: |
          # Create the deploy_key.pem file from the secret
          echo "$SSH_PRIVATE_KEY" > deploy_key.pem
          chmod 600 deploy_key.pem

          # SSH into the EC2 instance and deploy the changes
          ssh -o StrictHostKeyChecking=no -i deploy_key.pem $USER@$SERVER_IP "
            cd ~/your-fastapi-repo &&
            git pull origin main &&
            source venv/bin/activate &&
            pip install -r requirements.txt &&
            pkill -f 'uvicorn' || true &&
            nohup uvicorn app:app --host 0.0.0.0 --port 8000 &
          "
          echo "Deployment successful."
